#!/usr/bin/env node
/*
 * Generates src/data/cards.generated.ts from assets/cards/cards.csv.
 * Static require() literals per card (Metro needs literal paths). Run: npm run gen:cards
 */
const fs = require('fs');
const path = require('path');

const ROOT = path.join(__dirname, '..');
const CSV = path.join(ROOT, 'assets/cards/cards.csv');
const OUT = path.join(ROOT, 'src/data/cards.generated.ts');

// CSV pack name -> PackId / asset folder (folder === PackId).
const PACK_MAP = {
  Standard: 'standard',
  'The Tips': 'the-tips',
  League: 'league',
  Etiquette: 'etiquette',
  Mulligans: 'mulligans',
  Matchup: 'matchups',
};
const PACK_ORDER = ['standard', 'the-tips', 'league', 'etiquette', 'mulligans', 'matchups'];
const EXPECTED_COUNTS = { standard: 26, 'the-tips': 10, league: 18, etiquette: 10, mulligans: 18, matchups: 10 };
const EXPECTED_MULTI = ['Bounty', 'Putter Master', 'Not the Goat', 'Low Score'].sort();

// Reproduce the illustration filename slug (matches assets/cards/<pack>/<slug>.png).
function slugify(name) {
  return name
    .toLowerCase()
    .replace(/&/g, ' and ')
    .replace(/[‘’']/g, '') // strip apostrophes (curly + straight)
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-+|-+$/g, '');
}

// Minimal RFC-4180 parser (handles quoted fields with embedded commas/newlines/quotes).
function parseCsv(text) {
  const rows = [];
  let row = [], field = '', i = 0, inQuotes = false;
  const pushField = () => { row.push(field); field = ''; };
  const pushRow = () => { rows.push(row); row = []; };
  while (i < text.length) {
    const c = text[i];
    if (inQuotes) {
      if (c === '"') {
        if (text[i + 1] === '"') { field += '"'; i += 2; continue; }
        inQuotes = false; i++; continue;
      }
      field += c; i++; continue;
    }
    if (c === '"') { inQuotes = true; i++; continue; }
    if (c === ',') { pushField(); i++; continue; }
    if (c === '\r') { i++; continue; }
    if (c === '\n') { pushField(); pushRow(); i++; continue; }
    field += c; i++;
  }
  if (field.length > 0 || row.length > 0) { pushField(); pushRow(); }
  return rows;
}

function fail(msg) { console.error(`\n✗ gen-cards: ${msg}\n`); process.exit(1); }

const raw = fs.readFileSync(CSV, 'utf8').replace(/^﻿/, '');
const rows = parseCsv(raw).filter((r) => r.length > 1 && r.some((c) => c.trim() !== ''));
const header = rows.shift();
const col = (name) => header.indexOf(name);
const C = {
  pack: col('Pack'), name: col('Name'), challenge: col('Challenge'),
  multi: col('More than 1 winner'), type: col('Type'), how: col('How to Win'),
};
for (const [k, v] of Object.entries(C)) if (v < 0) fail(`CSV missing column for "${k}"`);

const cards = [];
const seenIds = new Set();
const multiNames = [];
const counts = {};
const missingArt = [];

for (const r of rows) {
  const packName = r[C.pack].trim();
  const packId = PACK_MAP[packName];
  if (!packId) fail(`unknown pack "${packName}" for card "${r[C.name]}"`);
  const name = r[C.name].trim();
  const slug = slugify(name);
  const id = `${packId}-${slug}`;
  const kind = r[C.type].trim() === 'Matchup' ? 'matchup' : 'individual';
  const multiWinner = r[C.multi].trim().toLowerCase() === 'yes';
  const challenge = r[C.challenge].trim();
  const howToWin = r[C.how].trim();

  if (seenIds.has(id)) fail(`duplicate id "${id}"`);
  seenIds.add(id);
  counts[packId] = (counts[packId] || 0) + 1;
  if (multiWinner) multiNames.push(name);

  // Illustration is expected but not required — a missing one renders the text placeholder.
  const png = path.join(ROOT, 'assets/cards/illustrations', packId, `${slug}.png`);
  const hasArt = fs.existsSync(png);
  if (!hasArt) missingArt.push(`illustrations/${packId}/${slug}.png ("${name}")`);

  // Cross-checks: Matchup pack <=> matchup kind; multiWinner only on matchup.
  if ((packId === 'matchups') !== (kind === 'matchup'))
    fail(`"${name}": matchups-pack and matchup-kind must agree (pack=${packId}, kind=${kind})`);
  if (multiWinner && kind !== 'matchup') fail(`"${name}": multiWinner only allowed on matchup cards`);

  cards.push({ id, name, pack: packId, kind, multiWinner, challenge, howToWin, slug, hasArt });
}

// Totals + per-pack counts.
if (cards.length !== 92) fail(`expected 92 cards, got ${cards.length}`);
for (const [pid, n] of Object.entries(EXPECTED_COUNTS))
  if (counts[pid] !== n) fail(`pack ${pid}: expected ${n} cards, got ${counts[pid] || 0}`);
const multiSorted = [...multiNames].sort();
if (JSON.stringify(multiSorted) !== JSON.stringify(EXPECTED_MULTI))
  fail(`multi-winner set mismatch. got ${JSON.stringify(multiSorted)}, expected ${JSON.stringify(EXPECTED_MULTI)}`);

// Emit, grouped by PACK_ORDER then CSV order.
cards.sort((a, b) => PACK_ORDER.indexOf(a.pack) - PACK_ORDER.indexOf(b.pack));
const s = (v) => JSON.stringify(v);
let out = `// AUTO-GENERATED by scripts/gen-cards.js — do not edit. Run \`npm run gen:cards\`.\n`;
out += `import type { Card } from './cards';\n\n`;
out += `export const CARDS: Card[] = [\n`;
let lastPack = null;
for (const c of cards) {
  if (c.pack !== lastPack) { out += `  // ---- ${c.pack} ----\n`; lastPack = c.pack; }
  out += `  { id: ${s(c.id)}, name: ${s(c.name)}, pack: ${s(c.pack)}, kind: ${s(c.kind)}, multiWinner: ${c.multiWinner}, `;
  out += `challenge: ${s(c.challenge)}, howToWin: ${s(c.howToWin)}`;
  out += c.hasArt ? `, image: require('../../assets/cards/illustrations/${c.pack}/${c.slug}.png') },\n` : ` },\n`;
}
out += `];\n`;

fs.writeFileSync(OUT, out);
console.log(`✓ gen-cards: wrote ${cards.length} cards to src/data/cards.generated.ts`);
for (const pid of PACK_ORDER) console.log(`    ${pid}: ${counts[pid]}`);
if (missingArt.length) {
  console.warn(`\n⚠ ${missingArt.length} card(s) with NO illustration (text placeholder will render):`);
  for (const m of missingArt) console.warn(`    ${m}`);
}
